version: 2

snapshots:
  - name: snap_customers_scd2
    description: "SCD Type 2 snapshot for customer master data (Timestamp strategy)"
    columns:
      - name: dbt_scd_id
        description: "Surrogate primary key for snapshot version"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Natural buisness key"
        tests:
          - not_null
          
  - name: snap_products_scd2
    description: "SCD Type 2 snapshot for product price and other import column changes"
    columns:
      - name: dbt_scd_id
        tests:
          - unique
          - not_null
          